### ISSUE TITLE
What does the new data set numbers stand for?

### ISSUE THREAD

**Issue by mithi** [udacity/CarND-Unscented-Kalman-Filter-Project#10]
So the new dataset has been uploaded 

https://raw.githubusercontent.com/udacity/CarND-Unscented-Kalman-Filter-Project/master/data/obj_pose-laser-radar-synthetic-input.txt

Here's an excerpt of 2 columns
```
L	3.122427e-01	5.803398e-01	1477010443000000	6.000000e-01	6.000000e-01	5.199937e+00	0	0	6.911322e-03
R	1.014892e+00	5.543292e-01	4.892807e+00	1477010443050000	8.599968e-01	6.000449e-01	5.199747e+00	1.796856e-03	3.455661e-04	1.382155e-02
```
It seems like there are 6 numbers after the timestamp,what do these measurement stand for?

In the old data set there where just  4 numbers after the timestamp which stood for 
`px, py, vx and vy`

**Comment by sookinoby** [comment]
@mithi It should be yaw and yaw rate.

**Comment by mithi** [comment]
@sookinoby  Okay thanks!
