### ISSUE TITLE
Disconnect between course instructions and program - NIS and Radar/Lidar

### ISSUE THREAD

**Issue by jorvidas** [udacity/CarND-Unscented-Kalman-Filter-Project#17]
Just an FYI, if you are reading through Project: Kalman Filters - Project Code and are looking for the code where NIS is output or where utilizing use_laser_ and use_radar_, they will need to be coded up yourself as they appear to have been removed from an earlier version of the repo but not removed from the course material.

**Comment by alexxucui** [comment]
Several students raised this question in the forum and I think the code is outdated and needs to be updated. Thanks!

**Comment by mvirgo** [comment]
Closing this out - `use_laser` and `use_radar` are still part of the `ukf.cpp` code, but up to student whether to implement or not. NIS is still a possible add, although not required, so I've updated the wording in the classroom to make that more clear.
